### PR TITLE
Rust CI fix

### LINKED ISSUE #4: CI is red
**Describe the bug**
CI is currently red.

**To Reproduce**

**Expected behavior**

**Additional context**

### PR DESCRIPTION
**Pull request by iajoiner**
# Which issue does this PR close?

Partly resolves #4.

 # Rationale for this change

# What changes are included in this PR?

# Are there any user-facing changes?

### CODE REVIEW

**Comment by iajoiner** [comment]
Let me get all the Rust stuff green.

**Comment by iajoiner** [comment]
@andygrove Could you please rerun the Github Actions? `clippy` and `tomlfmt` are green on my machine.

**Comment by andygrove** [comment]
@iajoiner Done. Maybe you need to `rustup update` to have same version of Rust as we use in CI?

**Comment by iajoiner** [comment]
Close in favor of #14.

**Pull request closed without merging**
